[package]
name = "oidc-filter"
version = "0.1.0"
authors = ["Daniel Grimm <dgrimm@redhat.com>"]
edition = "2021"

[dependencies]
proxy-wasm = "0.1.4"
log = "0.4.17"
url = "2.2.2"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.82"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
lto = true
