[package]
name = "oidc-filter"
version = "0.1.0"
authors = ["Daniel Grimm <dgrimm@redhat.com>"]
edition = "2018"

[dependencies]
proxy-wasm = "0.1.4"
log = "0.4.14"
url = "2.1.1"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
lto = true
